### ISSUE TITLE
Couverage Test Btree non disponible sur Test Runner

### ISSUE THREAD

**Issue by lydiatarmelit** [UnivLille-Meta/Miage23#58]
on trouve uniquement le base line de btree dans test Runner donc on ne peux pas obtenir le pourcentage de couverture de tests

**Comment by Ducasse** [comment]
Ok next one (like the initialize question) in english :) and in the BTree 
https://github.com/sebastianconcept/BTree

**Comment by guillep** [comment]
Closing this one
